sudo: false

language:
    - php
    - node_js

php:
    - 5.5

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=1
        - PHANTOMJS_CDNURL='http://files.urldocs.com/share/phantomjs'
        - GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER

branches:
    only:
        - master

before_install:
    - WP_VERSION=$( cat ./wp-includes/version.php | grep 'wp_version =' | grep -oE '[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)*(-[0-9a-z]*)*' )
    - echo "WP_VERSION=$WP_VERSION"

install:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - set -x
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh

after_success:
 #- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git config --global user.email "merenuou@yahoo.com"
  - git config --global user.name "Obi Did this"
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER" 
  - git push -q https://github.com/OWL-Labs/WordPress.git --tags
  - ls -R

notifications:
